// This file will be auto-generated by Amplify after first deployment
// For now, use environment variables for API URL
const config = {
  API: {
    REST: {
      salesPortalAPI: {
        endpoint: process.env.REACT_APP_API_URL || '',
        region: 'us-east-1',
      },
    },
  },
};

export default config;
